version: "3.8"
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j_db
    ports:
      - "7474:7474"  # HTTP interface for the Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data

  loader:
    build: .
    depends_on:
      - neo4j
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    restart: "no"  # only run once

volumes:
  neo4j_data:
